# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r: bioc-release
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

before_script:
  - echo "BiocParallel::register(BiocParallel::SerialParam())" > ~/.Rprofile
